### ISSUE TITLE
Phoenix 4.5 released

### ISSUE THREAD

**Issue by chiastic-security** [cloudera-labs/phoenix#1]
Cloudera Labs Phoenix is now two versions behind: it is on Phoenix 4.3, but Phoenix 4.5 has now been released.

Could the repo please be updated to add support for Phoenix 4.5?

**Comment by kverhoeven** [comment]
Phoenix is incredibly useful, do you know when the version will be updated from 4.3 to 4.5? The use of WAL against HBase and SQL-like interpretation make this one of the most important Parcels CDH can offer my company.

**Comment by ar996** [comment]
Does Cloudera give up  on  this project ?

**Comment by busbey** [comment]
a CLABS update for phoenix 4.5 happened back in November:

http://blog.cloudera.com/blog/2015/11/new-apache-phoenix-4-5-2-package-from-cloudera-labs/
