### ISSUE TITLE
Support for Custom build for CDH versions

### ISSUE THREAD

**Issue by mohanaugust** [cloudera-labs/phoenix#3]
I am using CDH 5.7.1 with the current version of Phoenix from CDH parcels. I am getting errors because of Jar mismatch. Can you please let us know of there is support for a custom build for the particular version of CDH used by the customer.

**Comment by busbey** [comment]
if you are using CDH5.7.1, then [you ought to be using the Cloudera Labs packaging referenced in this announcement](community.cloudera.com/t5/Cloudera-Labs/ANNOUNCE-Third-installment-of-Cloudera-Labs-packaging-of-Apache/m-p/42351).
